### ISSUE TITLE
添加 post 组件的 样式问题

### ISSUE THREAD

**Issue by liangtj** [Chun-Ge/Shudong-FrontEnd#10]
那个样式不居中啊，**+号** 位于上方，而不是垂直居中，fix一下 @Binly42 
![image](https://user-images.githubusercontent.com/16269231/40599172-73e9ed8a-627e-11e8-901b-1ab48e1df877.png)

**Comment by Binly42** [comment]
... 不知什么原因, 现在发现它好像已经居中了, close 了得了 (
