### ISSUE TITLE
关于 组件库自带的 Dropdown 和 Modal 之间的堆叠行为混乱 及 解决方案

### ISSUE THREAD

**Issue by Binly42** [Chun-Ge/Shudong-FrontEnd#6]
比如, 现在的 `举报帖子` 功能, 点击 "举报滥用行为" 后, 还没消失的 Dropdown 列表 就可能会出现在 弹出的 举报 Modal 之上 ; 
而现在用着的解决方案是全局性的钦定 Modal 的 `z-index` 大于 Dropdown, 这个泄漏到其他地方造成的影响比较尴尬 ...

而组件库自带的组件的样式行为是既定的, 而且是自动插入到 DOM 的顶层的 ... 现在看来没找到什么有效且合理的方法覆盖原有的样式行为 ... (`!important` 毕竟还是不太好吧 ... 而且目前代码基础上我有遇到即使用了 `!important` 也无效的情况, 不过这个我还没细究)

现在考虑的替代方案有:
1. 动态的调整 `z-index` ; 我觉得这个更直观, 也更通用 ;
2. 二者之间视情况建立 对立 的存在/可见关系, 就这里的例子而言可以简单地用其中一个的可见性作条件判断渲染 ; 我觉得这个可能会简单讨巧一点, 但是效果可能有点折扣(毕竟二者外的其他元素也需要考虑...)

我现在先用着 **2.** 糊了我的任务, 之后可以再讨论

**Comment by liangtj** [comment]
大佬
